### ISSUE TITLE
Add check method to myzod

### ISSUE THREAD

**Issue by kasperpeulen** [davidmdm/myzod#19]
I was thinking about a method like this as in zod:

![image](https://user-images.githubusercontent.com/1035299/87785882-46847b80-c839-11ea-8c37-7dcee20ce559.png)

However, myzod is of course quite fundamental dififerent as zod, as myzod does sometimes type coercion (for numbers, date and arrays), and fills in default values, while zod just gives back the input in the parse method (or throws an error).

Personally, I think the type coercion feature is great, (I think json type coercion for objects would be great as well). It prevents me from having to deal with multiple different data types. For example, in zod, first parse the method as special strings, (isostrings, comma seperated list), then cast the types to types you need manually (Date, Array, etc.), and then maybe parse again, with a new schema, to make sure the array has the right kind of elements.

However, because of the type coercion in myzod, implementing a check method becomes a bit more challenging, see the failing tests in this PR: https://github.com/davidmdm/myzod/pull/18/files

How I see this, is that a `check` method could work very much like a much more flexible `instanceof` check, but then for plain javascript objects. For example:

```ts
const A = object({ a: number().coerce(), common: string() });
const B = object({ b: string(), common: string() });
const schemaUnion = union([A, B]);

const raw: unknown = { a: '1', common: 'string' }
const data = schemaUnion.parse(raw);

if (A.check(data)) {
  console.log(data.a); // TS knows now that the type is A
} else {
  console.log(data.b); // TS knows that the type is B
}
```

To make both coercion and the check method work with myzod, I think we would need to split up the parse process in two.

```ts
export abstract class Type<T> {
  constructor() {}

  /** Here it only checks if the filled in value matches the schema. */
  abstract check(value: unknown): value is T;

  /** Here coercion happen and default values are filled. */
  abstract cast(value: unknown): T;

  parse(value: unknown): T {
    const castedValue = this.cast(value);
    this.check(castedValue);
    return castedValue;
  }
}
```

**Comment by davidmdm** [comment]
Sorry for the late reply, just been a little caught up at work.

Yeah I decided to forgo check in lieu of type coercion. I do have the check type guard on the enum schema for example because in that case I can confidently check it because no type coercion is involved.

As an alternative to a standard typeguard, but allowing for type-safety and coercion, there's the `try` api that returns the parsed value or an error. It's not quite as inline-able as `check` but better than `parse` and feels similar to a type guard.

```typescript
const value = schema.try(unknownData);
if (value instanceof Error) {
  // handle the validation error
} else {
  // value is correctly typed: Infer<typeof schema>
}
```

I was wondering if you knew about the `try` api before proposing `check`? If not, does it help your use case / inter-play with coercion. If so, do you think the check api is worth the trouble of getting it to mesh with type coercion?
