### ISSUE TITLE
How / Why Is MyZod Faster Than Zod

### ISSUE THREAD

**Issue by supermacro** [davidmdm/myzod#37]
Just ran into this library and am curious to learn / understand how you managed to get a 25x improvement on parsing compared to zod.

Any big tradeoffs that were made here?

**Comment by davidmdm** [comment]
it's actually closer to over a hundred X now. I haven't really updated the docs in a while with regards to performance.
The main difference is in the parsing. In myzod each type implements it's own parse. Object parsing has 12 different variants of parse given the object shape for example. Whether or not a keysignature is set etc. 

Also as much as possible schemas are prebuilt ahead of time inside the constructors of various different Type classes.

Zod has a single parse function which runs over many different select statements. I think due to it's size it cannot easily be inlined by V8, and if statements and switches add up.

That being said myzod is definitely not the fastest library by a long shot. However I do think it strikes a balance in terms of being decently featured, small, and fast.

I don't think myzod sacrificed anything in order to get speed other than a little bit of duplicated code with small variations.
Try it and let me know what you think :)
