### ISSUE TITLE
Suggestion: `required` operator

### ISSUE THREAD

**Issue by zhaoyao91** [davidmdm/myzod#39]
if a field is already optional, we have no way to make it required, which prevent us from reusing other schemas.

**Comment by davidmdm** [comment]
I have added a required method for optional and nullable schemas. It was released just now in version 1.7.0

Let me know if this solves your issue.

Thanks.

**Comment by zhaoyao91** [comment]
I see both optional and nullable use require as revert. What happens when I call require on an optional and nullable schema?

**Comment by davidmdm** [comment]
Well if it was optional and nullable, you would have to call required twice, I figured because it is static you it’s not too confusing and it gives the power of removing either wrapper without removing both. 

I was considering adding a more generic helper function that would unwrap a schema recursively but didn’t add that on a first draft. Is that more what you had in mind?

**Comment by davidmdm** [comment]
Ok I added `mzyod.required()` in v1.7.1

It calls required on the schema until the top level schema no longer has an optional or nullable schema wrapper.

```typescript
const optionalSchema = z.string().optional().nullable();

const schema = z.required(optionalSchema) // Simpy a StringType schema.
```

**Comment by zhaoyao91** [comment]
Oops, it's very helpful! Thanks very much.
