### ISSUE TITLE
How can I extend object?

### ISSUE THREAD

**Issue by Code-Hex** [davidmdm/myzod#51]
zod has been supported [extend](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/main/example/zod) API. Is it possible like this in myzod also?

**Comment by davidmdm** [comment]
No, there is no extend API.
Since schema's should be static for best performance, it was not deemed an important feature.
However you can manipulate schemas by using `omit` and intersections. 

Myzod aims to be a simpler more performant version of zod not to be a 1:1 reimplementation.

It was very useful when zod was not performant enough to be viable on the server, but I believe that has changed recently.
