### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by pierreis** [davidmdm/myzod#9]
Hi @davidmdm -- would you be open to add a method `Type.default(T | () => T)`, that would set the default value on parse as the provided value if it is unknown?

That would be such that:

```ts
const userSchema = mz.Object({
    id: mz.string().default(uuidv4),
    name: mz.string(),
})
userSchema.parse({ name: "John" }); // => { id: "2c5ea4c0-4067-11e9-8b2d-1b9d6bcdbbfd", name: "John" }

const stringSchema = mz.string().default("hello");
stringSchema.parse(undefined); // => "hello"
```

There are probably a few edge cases in implementing this, but I believe it would avoid a lot of boilerplate code when processing input API data.

**Comment by davidmdm** [comment]
I think it's a good idea. It is very similar to a what joi gives you. It may affect performance slightly but probably not dramatically. This api reminds a lot of Joi and was something I used fairly often when creating Joi schemas. 

I'll get to work on it in the next couple days.

**Comment by pierreis** [comment]
Sounds good. The only edge case I can see are lazy types, but not quite sure about this. Regardless, I think that would be a great feature that would make my code significantly more straightforward.

Do you need help with this?

**Comment by davidmdm** [comment]
If you want to implement it that's fine by me. Otherwise I'll get to it probably tomorrow or tuesday. I just got a couple unrelated coding things going on right now that are higher priority. You can have a stab at it if you like.

I always have misgivings about putting it on the prototype of the parent `Type` class. 

Does it matter that putting it on the Type class allows for this redundant scenario?
```typescript
mz.undefined().default(undefined);
```
I guess probably not. It's the only one I can think of.

Also as for the parsing, I think the simplest solution is to add it into the parse signature as a default value to the argument:
```typescript
parse(value: unknown = typeof this.default  === 'function' ? this.default() : this.default)
```
this way the default value still runs through your predicate functions and you don't have to deal with assignation logic in the body of the function. 

As for lazy types I think the only danger is we risk creating circular object / infinite loops. Myzod currently does not support it. I have a longstanding branch for this issue. I think we could go ahead with default, and revisit supporting circular objects for lazyTypes later.

What do you think?

**Comment by davidmdm** [comment]
oops just meant to comment... not close and comment...

**Comment by pierreis** [comment]
No worries.

I would say that regarding infinite loops, it should probably be up to the developer to understand the possibility of this happening. I don't see it as a major issue. Same goes for the redundant example of `undefined` -- you can do it, sure, but I am quite sure it is not a problem.

Regarding the implementation, I have to admit I had no idea it was possible to perform a function call from a default function parameter. This looks good! -- I would only normalize a literal as a function at the point of entry 😄 
~~Only the implementation of `ObjectType.parse()` will have to be modified I think ; as of now, it does not iterate on the fields of the shape.~~

No hurry here. I am not yet sure whether or not I will be able to tackle this before you do though.

**Comment by davidmdm** [comment]
Yeah I wasn't sure about the function call in the default argument position. I tried it in the terminal before posting that just to be sure I wasn't crazy!

I am not sure what you mean about ObjectType.parse?

Kk cool. I'll get on it tomorrow :)

**Comment by pierreis** [comment]
Nevermind that comment. I read your code a bit too quickly, it is all good!

**Comment by davidmdm** [comment]
@pierreis This has been merged and publish to v1.0.0-alpha.8

Thanks again for the issue and your collaboration.
Closing the issue now!

**Comment by pierreis** [comment]
You're most welcome!

You did probably miss one comment of mine on the pull request though:

```ts
const schema = z.object({
  a: z.string().default('hello'),
}).default({});

// Does not compile, because `a` is not optional.
// The problem is that in this case, the type of the default value should be a subset of
// the object having at least all required, non-defaulted fields.
// Marking the field as optional works, but messes with the inferred type.
```

```ts
const schema = z.object({
  a: z.string().optional().default('hello'),
}).default({});

// Does not compile either, because `OptionalType` is not `Defaultable`.
// It should probably be when the wrapped type is.
```

One issue in particular seems rather problematic:

```ts
const schema = z
  .object({
    a: z.string().default('hello').optional(),
  })
  .default({});

schema.parse(undefined)); // => { a: undefined } instead of the expected { a: 'hello' }
```

I think this should be fixed before releasing.

**Comment by davidmdm** [comment]
@pierreis 

I didn't see that comment. But I did notice the case you mentioned when testing:
```typescript
const schema = z.object({  a: z.string().default('hello') }).default({});
```
and my thinking was that it was more trouble than it's worth. If you know the default object you might as well put it as the default, instead of an object that will depend on the defaults of its inner schema. 

Also I am not sure how I would go about typing it such that only defaultable keys in the objectSchema become optional to the default method. So regardless I think that might just be on ice.

But you are correct that this expression is definitely confusing: 
```typescript
z.string().default('hello').optional()
```
In both directions its a little confusing, should the default be preserved? Or should optional void the default value?

I could have the OptionalType wrapper peak inside it's inner schema for a defaultValue.

**Comment by pierreis** [comment]
I don't think it is too complicated to do it in both cases. I definitely think that OptionalType should peek into the nested schema -- this would also solve the `const schema = z.object({  a: z.string().optional().default('hello') }).default({});` case, killing two birds with one stone.

I don't necessarily agree with you on the fact that I may pass the default for nested values right inside the object, as it breaks encapsulation. If I have an `addressSchema` nested inside some `aserSchema`, I would need to do the following:

```ts
const userSchema = z.object({
  id: z.string(),
  address: addressSchema,
}).default({
  id: uuidv4,
  address: addressSchema.parse(undefined),
})
```

While this is technically not impossible, it is not very pretty either. Maybe we could add some parameterless `default()` method that will return the default value, so the above would be:

```ts
const userSchema = z.object({
  id: z.string(),
  address: addressSchema,
}).default({
  id: uuidv4,
  address: addressSchema.default(),
})
```

It is still not ideal, but does look a tad more expressive at the very least.

**Comment by pierreis** [comment]
In the long run, I might try an implementation based on a `DefaultedType<T>` class, similar to what you have done for `OptionalType` and `NullableType`, that would likely solve each point.

**Comment by davidmdm** [comment]
Yeah I was thinking along the samelines for DefaultedType<T>... Otherwise there's no easy way to do type inference on object keys. If you do that though once you default a schema you can no longer use that schema's methods.

```typescript
z.object({ ... }).default(...).partial/pick/omit()
```

At the same time that is already the case when calling optional/nullable.
I think I will explore this solution. It'll probably have a lot less boilerplate as well. 

However I don't like this:
```typescript
z.string().default().nullable().default() => Defaultable<Nullable<Defaultable<StringType>>>
```

But I guess that is fine... The top level Defaultable wins out, and the inner defaultable stringtype could still be reused elsewhere...

**Comment by pierreis** [comment]
Agree on the last point. Probably not a big deal ; IMO it falls in the "sure you can do it, but not a big deal" category. Not being able to use nested methods is indeed a bit disturbing. I think the problem is already existing with `optional().nullable().optional()`.

I wonder whether creating a "Proxy" class could be an option here: dynamically using `defineProperty` on these `Nullable`, `Optional` and so forth to create proxy methods, and redefine `optional()` as returning `OptionalType<this> & this` instead of just `OptionalType<this>`. This would work, but not quite sure whether or not I like it.

**Comment by davidmdm** [comment]
I have been sitting on this for a couple days as I recharged my batteries.
I think this case is ok as is:

```typescript
const schema = mz.string().default(uuid).optional()
```
The fact that the optional voids the default is ok because this is what the type hint gives you. `Infer<typeof schema> === string | undefined`

Also it is still easily composable:

```typescript
const uuidSchema = z.string().withPredicate(isUUID).default(uuidv4);
const querySchema = z.object({ id: uuidSchema.optional(), otherField: otherSchema.optional(), ... });
```
In the querySchema you may want to use your defined UUID schema but truly make it optional. Even if it has a default for when used non-optionally.

As for the DefaultType debacle / Making defaulted keys optional to the `default()` I don't think it is worth the sacrifice of deep partial schemas. It will have to be revisited should I decide to try and refactor all the type declarations and try to simplify but that will be a separate effort... For now I think I will close and keep in mind the DefaultType as  possibility in the future.
